In [7]:
# Create a list of first 10 square numbers"
num=1
list=[]
for i in range(1,11):
    num=i**2
    list.append(num)
print(f"the squared list is:{list}")



the squared list is:[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [9]:
## Find the sum of all even numbers in [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]"
list= [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
sum=0
for i in list:
    if i%2==0:
        sum=sum+i

print(f"the sum of even number in the list is :{sum}")

the sum of even number in the list is :30


In [12]:
## Remove duplicates from [1, 2, 2, 3, 4, 4, 5, 6, 6, 7]"
list=[1, 2, 2, 3, 4, 4, 5, 6, 6, 7]
remove=set(list)
print(remove)

{1, 2, 3, 4, 5, 6, 7}


In [30]:
## Sort the list [64, 34, 25, 12, 22, 11, 90] in descending order"
l=[64, 34, 25, 12, 22, 11, 90]
sorted=l.sort(reverse=True)
print(sorted)

None


In [1]:
## Find the average of numbers in [15, 23, 31, 42, 56, 78, 91]"
given=[15, 23, 31, 42, 56, 78, 91]
for i in given:

    avg=sum(given)/len(given)
print(avg)

48.0


In [2]:
##  Create a list of first 15 Fibonacci numbers")
fib=[0,1]
for i in range(2,15):
    fib.append(fib[i-1]+fib[i-2])
print(f"fibonacci series is:{fib}")


fibonacci series is:[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377]


In [8]:
## Find the second largest number in [45, 67, 23, 89, 12, 34, 78]"
n=[45, 67, 23, 89, 12, 34, 78]
lagest=max(n)
n.remove(lagest)
second_largest=max(n)
print(second_largest)


78


In [17]:
## Reverse the list [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
l=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
reversed=l[::-1]
print(reversed)



[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]


In [19]:
###  Count how many times 5 appears in [1, 5, 2, 5, 3, 5, 4, 5, 6]

m=[1, 5, 2, 5, 3, 5, 4, 5, 6]
count=0
for i in m:
    if i==5:
        count+=1
    else:
        pass
print(count)

4


In [21]:
##  Create a list of prime numbers between 1 and 50
k=[]

for i in range(2,50):
    if i%2==0:
        pass
    else:
        k.append(i)
print(k)


[3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49]


In [24]:
## Flatten nested list [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
li=[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
flat=[]
for i in li:
    for k in i:
        flat.append(k)
print(flat)


[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [31]:
## Find common elements between [1, 2, 3, 4, 5] and [4, 5, 6, 7, 8]
a=[1, 2, 3, 4, 5]
b=[4, 5, 6, 7, 8]
c=(set(a)& set(b))
print(c)

{4, 5}


In [32]:
##  Create a list of lists: [[1, 2], [3, 4], [5, 6]]
k=[[1, 2], [3, 4], [5, 6]]
print(k)

[[1, 2], [3, 4], [5, 6]]


In [33]:
 ##Find the sum of each sublist in [[1, 2, 3], [4, 5, 6], [7, 8, 9]]")
lists=[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
for list in lists:
    for i in list:
        total=sum(list)
    print(total)

6
15
24


In [13]:
## Transpose the matrix [[1, 2, 3], [4, 5, 6], [7, 8, 9]]")
import numpy as np



matrix=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
transpose=matrix.T
print(transpose)


[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [3]:
## Find the maximum value in each sublist of [[1, 5, 3], [9, 2, 7], [4, 8, 6]]")
list=[[1, 5, 3], [9, 2, 7], [4, 8, 6]]
for i in list:
    max_num_in_sublist=max(i)
    print(f"max value in {i} sublist is:{max_num_in_sublist}")

max value in [1, 5, 3] sublist is:5
max value in [9, 2, 7] sublist is:9
max value in [4, 8, 6] sublist is:8


In [ ]:
## Create a 3D list: [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]


In [ ]:
##  Find the sum of all elements in 3D list [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]

In [2]:
##Find the sum of all elements in 3D list [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
list=[[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
set_of_list=set(list)
sum_of_list=sum(set_of_list)
print(sum_of_list)

TypeError: unhashable type: 'list'

In [35]:
## Extract all even numbers from nested list [[1, 2, 3], [4, 5, 6], [7, 8, 9]]")
list=[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
lists=[]
for i in list:
    for j in i:
        if j%2==0:
            lists.append(j)
print(lists)

[2, 4, 6, 8]


In [37]:
## Create a list of mixed data types:
differ=[1, 'hello', 3.14, True, [1, 2, 3]]
print(differ)

[1, 'hello', 3.14, True, [1, 2, 3]]


In [41]:
##  Find the length of each string in ['apple', 'banana', 'cherry', 'date']
items=['apple', 'banana', 'cherry', 'date']
for i in items:
    for j in i:
        lenght=len(i)
    print(lenght)

5
6
6
4


In [52]:
##  Create a list of tuples: [(1, 'a'), (2, 'b'), (3, 'c')]
l=[(1, 'a'), (2, 'b'), (3, 'c')]
k=[]
for i in l:
    for j in i:
        k.append(j)
print(k)

[1, 'a', 2, 'b', 3, 'c']


In [56]:
## Extract first element from each tuple in [(1, 'a'), (2, 'b'), (3, 'c')]
tuples = [(1, 'a'), (2, 'b'), (3, 'c')]
first_elements = []

for t in tuples:
    first_elements.append(t[0])

print(first_elements)


[1, 2, 3]


In [16]:
# Create a list of dictionaries: [{'name': 'Alice', 'age': 25}, {'name': 'Bob', 'age': 30}]"
data = []

person1 = {'name': 'Alice', 'age': 25}
person2 = {'name': 'Bob', 'age': 30}

data.append(person1)
data.append(person2)

print(data)


[{'name': 'Alice', 'age': 25}, {'name': 'Bob', 'age': 30}]


In [17]:
## Extract all 'name' values from list of dictionaries"
dic=[{'name': 'Alice', 'age': 25},
    {'name': 'Bob', 'age': 30}
]
names=[]
for i in dic:
    names.append(i['name'])
print(names)

['Alice', 'Bob']


In [18]:
## Find the person with maximum age in list of dictionaries
people=[{'name': 'Alice', 'age': 25},
    {'name': 'Bob', 'age': 30}]
max_person = people[0]

for person in people:
    if person['age'] > max_person['age']:   # dictionary indexing operator
        max_person = person

print(max_person)

{'name': 'Bob', 'age': 30}


In [21]:
## Create a list of sets: [{1, 2, 3}, {4, 5, 6}, {7, 8, 9}]
l=[]
l.append({1,2,3})
l.append({4,5,6})
l.append({7,8,9})

print(l)

[{1, 2, 3}, {4, 5, 6}, {8, 9, 7}]


In [23]:
## Find the union of all sets in list of sets"
s=[{1, 2, 3}, {4, 5, 6}, {8, 9, 7}]
result=set()
for i in s:
    result=result.union(i)
print(result)

{1, 2, 3, 4, 5, 6, 7, 8, 9}


In [1]:
## Check if string is a valid email format: 'user@example.com
email="darshandremar@gmail.com"
if '@' in email and '.' in email.split('@')[-1]:
    print("valid email")
else:
    print("Invalid email")

valid email


In [13]:
## Extract domain from 'https://www.example.com/path
link='https://www.example.com/path'
domain= link.split('//') and link.split('/')[2]
print(domain)
   

www.example.com


In [17]:
## Count lines in multi-line string
string="""Hello,
Welcome to Python programming.
This is a multi-line string example."""

lenght=len(string.splitlines())
print(f"no of lines:{lenght}")



no of lines:3


In [26]:
##  Find common characters between 'hello' and 'world'
a="hello"
b="world"
comman=set(a) & set(b)
print(comman)


{'o', 'l'}


In [ ]:
##  Check if string is a valid phone number: '+1-555-123-4567'
phone_number='+1-555-123-4567'
for i in phone_number(15):
    if phone_number.startswith('+1') and phone_number.count


Login successfull
